### ISSUE TITLE
Let's clean up the branches

### ISSUE THREAD

**Issue by datagrok** [oc-elixir-elm/diamondback-railroad#1]
I'd like to clean up the branches in this repo to simplify things. As I understand it, there's `master` which was written for elm 0.16, and `elm17` represents a long-running branch rewrite for Elm 0.17. I'd leave those alone.

According to `git branch -a --merged master`, the branches `convert_svg_to_element` and `element` branches are fully included in the history of `master`, so we can delete those branches. If it's important for some reason to mark the commits where they existed, we could apply a tags there instead.

Similarly, according to `git branch -a --merged elm17`, the branches `final` and `hackfest` are fully included in the history of `elm17` so it is safe to delete them too.

Finally, the branches `collage`, `single_source_page`, `simplify`, `mess`, and `temp` seem to be old (abandoned?) branches, not merged back into `master` nor `elm17`, some of which include others in their history. I think we could probably remove at least some of them, or rename to something more descriptive, or maybe have username or purpose prefixes like `tl-svg` or `experiments/single_source_page`.

Finally, let's rename `working` to `elm17-wip` or `elm17-next`.

Agree? Disagree? I won't touch anything without some approval :smiley:

**Comment by oldfartdeveloper** [comment]
Hi Michael,

I started cleaning up the branches over the weekend; didn't get as far as I
wanted to.

In general, most of the branches are back in Elm 0.16.  Since, for this
exercise, we're emphasizing Html and Svg over Graphics, I think we can
delete all the old 0.16 branches.  Also, we can delete the 0.17 branches
that are, as you noted, already merged into elm17.  Hence, as you suggest,
all of the following branches can be deleted.
- convert_svg_to_element
- element
- final
- hackfest
- collage
- single_source_page
- simplify
- mess
- temp

Finally For renaming, I like renaming working to elm17-wip.

Thank you for your detailed analysis and suggestions.  It helped goad me
into some decisions that, deep down, I knew I was going to have to make
anyways.

Now that you have done the high-level approach, please go ahead and do it
or ping me and I'll to it.

For the future, I think we need to agree on a process for deciding when to
merge our development branch (quickly to become elm17-wip) to master.  We
can discuss that next meeting.

Again, thanks! 👍

On Sat, May 21, 2016 at 10:47 PM, Michael F. Lamb notifications@github.com
wrote:

> I'd like to clean up the branches in this repo to simplify things. As I
> understand it, there's master which was written for elm 0.16, and elm17
> represents a long-running branch rewrite for Elm 0.17. I'd leave those
> alone.
> 
> According to git branch -a --merged master, the branches
> convert_svg_to_element and element branches are fully included in the
> history of master, so we can delete those branches. If it's important for
> some reason to mark the commits where they existed, we could apply a tags
> there instead.
> 
> Similarly, according to git branch -a --merged elm17, the branches final
> and hackfest are fully included in the history of elm17 so it is safe to
> delete them too.
> 
> Finally, the branches collage, single_source_page, simplify, mess, and
> temp seem to be old (abandoned?) branches, not merged back into master
> nor elm17, some of which include others in their history. I think we
> could probably remove at least some of them, or rename to something more
> descriptive, or maybe have username or purpose prefixes like tl-svg or
> experiments/single_source_page.
> 
> Finally, let's rename working to elm17-wip or elm17-next.
> 
> Agree? Disagree? I won't touch anything without some approval 😃
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/oc-elixir-elm/diamondback-railroad/issues/1

## 

Scott Smith

http://twitter.com/_ofd (OldFartDeveloper)

**Comment by oldfartdeveloper** [comment]
I've made @datagrok's suggested changes and so am closing this issue.
